### ISSUE TITLE
Add not, any, all, some, none interface variants of xtype.is

### ISSUE THREAD

**Issue by noahrc** [lucono/xtypejs#12]
Thanks for the 0.6 modularity update!

I think it would be helpful to have an isNot method for readability. Instead of something like this:

`!xtype.is(data, 'obj')`

I'd like to be able to write `xtype.isNot(data, 'obj')`

Also, xtype.not.is() throws an error (but I don't like that form anyway).

**Comment by lucono** [comment]
Hi Noah, this will be included in the next release (v0.7.0).

It is likely to be `xtype.not.is(value, types)`, which fits better with the existing xtypejs API, rather than `xtype.isNot(value, types)`.

For completeness to the `xtype.is` API, the release will also include `none.is`, `any.is`, `some.is` and `all.is`, in addition to `not.is`.

**Comment by noahrc** [comment]
Cool, thanks for the update!

**Comment by lucono** [comment]
Resolved with release of v0.7.0.

See documentation for full set of API methods (including the new ones) [here](http://xtype.js.org/api).
